In [50]:
#  Tic-Tac-Toe
#  plays multiple random games; accumulates stats
#  gw

import random

# global
Board = [[' ', ' ', ' '],
         [' ', ' ', ' '],
         [' ', ' ', ' ']]


def resetBoard():
    global Board
    Board = [[' ', ' ', ' '],
             [' ', ' ', ' '],
             [' ', ' ', ' ']]


# display game state
def printBoard():
    print(Board[0][0], ' | ', Board[0][1], ' | ', Board[0][2])
    print('-------------')
    print(Board[1][0], ' | ', Board[1][1], ' | ', Board[1][2])
    print('-------------')
    print(Board[2][0], ' | ', Board[2][1], ' | ', Board[2][2])
    print()


# choose random legal move
def doMove():
    while True:
        x = random.randrange(3)
        y = random.randrange(3)
        if Board[x][y] == ' ':
            break
    return x, y


# test game status
def gameWon(piece):
    if (((Board[0][0] == piece) and (Board[0][1] == piece) and (Board[0][2] == piece))
            or ((Board[1][0] == piece) and (Board[1][1] == piece) and (Board[1][2] == piece))
            or ((Board[2][0] == piece) and (Board[2][1] == piece) and (Board[2][2] == piece))
            or ((Board[0][0] == piece) and (Board[1][0] == piece) and (Board[2][0] == piece))
            or ((Board[0][1] == piece) and (Board[1][1] == piece) and (Board[2][1] == piece))
            or ((Board[0][2] == piece) and (Board[1][2] == piece) and (Board[2][2] == piece))
            or ((Board[0][0] == piece) and (Board[1][1] == piece) and (Board[2][2] == piece))
            or ((Board[0][2] == piece) and (Board[1][1] == piece) and (Board[2][0] == piece))):
        return True
    else:
        return False


# run a whole bunch of games
# note: X always goes first
Xcount = 0
Ocount = 0
Drawcount = 0
# games = int(input('#games? '))
games = 1
for i in range(games):
    resetBoard()
    numMoves = 0
    done = False
    while not done and (numMoves < 9):
        numMoves += 1
        if (numMoves % 2) == 1:
            piece = 'X'
        else:
            piece = 'O'
        x, y = doMove()
        Board[x][y] = piece
        if gameWon(piece):
            done = True
            if piece == 'X':
                Xcount += 1
            else:
                Ocount += 1
        if (numMoves == 9) and not done:
            Drawcount += 1

print('X wins: ', round(100.0 * Xcount / games), '%')
print('O wins: ', round(100.0 * Ocount / games), '%')
print('Draw  : ', round(100.0 * Drawcount / games), '%')


X wins:  0 %
O wins:  100 %
Draw  :  0 %


In [56]:
str(Board)

"[[' ', 'X', 'O'], ['X', 'O', 'O'], ['X', 'X', 'O']]"

In [ ]:
import numpy as np



In [ ]:
epsilon = 0.9
discount_factor = 0.9
learning_rate = 0.9

win_reward = 1
lose_reward = -1
draw_reward = 0


# initialize q-values as 0
Q = [[]]

for episode in range(10):
    resetBoard()
    numMoves = 0
    done = False
    states_history = []
    while not done and (numMoves < 9):
        numMoves += 1
        if (numMoves % 2) == 1:
            piece = 'X'
        else:
            piece = 'O'
        x, y = doMove()
        Board[x][y] = piece
        states_history.append(str(Board))
        if gameWon(piece):
            done = True
            if piece == 'X':
                Xcount += 1
                s2 = states_history[len(states_history)-1]
                s1 = states_history[len(states_history)-1 - 2]
                Q[s1, s2] =
            else:
                Ocount += 1

        if (numMoves == 9) and not done:
            Drawcount += 1

In [70]:
np.zeros([10000,10000])

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [47]:
import numpy as np

# Q 矩阵初始化为0
q = np.matrix(np.zeros([6, 6]))

# Reward 矩阵为提前定义好的。 类似与HMM的生成矩阵。-1表示无相连接的边
r = np.matrix([[-1, -1, -1, -1,  0,  -1],
               [-1, -1, -1,  0, -1, 100],
               [-1, -1, -1,  0, -1,  -1],
               [-1,  0,  0, -1,  0,  -1],
               [ 0, -1, -1,  0, -1, 100],
               [-1,  0, -1, -1,  0, 100]])

# hyperparameter
#折扣因子
gamma = 0.8
#是否选择最后策略的概率
epsilon = 0.4
# the main training loop
for episode in range(101):
    # random initial state
    state = np.random.randint(0, 6)
    # 如果不是最终转态
    while (state != 5):
        # 选择可能的动作
        # Even in random case, we cannot choose actions whose r[state, action] = -1.
        possible_actions = []
        possible_q = []
        for action in range(6):
            if r[state, action] >= 0:
                possible_actions.append(action)
                possible_q.append(q[state, action])

        # Step next state, here we use epsilon-greedy algorithm.
        action = -1
        if np.random.random() < epsilon:
            # choose random action
            action = possible_actions[np.random.randint(0, len(possible_actions))]
        else:
            # greedy
            action = possible_actions[np.argmax(possible_q)]

        # Update Q value
        q[state, action] = r[state, action] + gamma * q[action].max()

        # Go to the next state
        state = action

    # Display training progress
    if episode % 10 == 0:
        print("------------------------------------------------")
        print("Training episode: %d" % episode)
        print(q)

------------------------------------------------
Training episode: 0
[[  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0. 100.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]]
------------------------------------------------
Training episode: 10
[[  0.    0.    0.    0.   51.2   0. ]
 [  0.    0.    0.   64.    0.  100. ]
 [  0.    0.    0.   64.    0.    0. ]
 [  0.   80.    0.    0.   51.2   0. ]
 [  0.    0.    0.   64.    0.    0. ]
 [  0.    0.    0.    0.    0.    0. ]]
------------------------------------------------
Training episode: 20
[[  0.    0.    0.    0.   51.2   0. ]
 [  0.    0.    0.   64.    0.  100. ]
 [  0.    0.    0.   64.    0.    0. ]
 [  0.   80.   51.2   0.   51.2   0. ]
 [  0.    0.    0.   64.    0.    0. ]
 [  0.    0.    0.    0.    0.    0. ]]
------------------------------------------------
Training episode: 30
[[  0.    0.    0.    0.   51.2   0. ]
 [  0.    0. 

array([[ -1,  -1,  -1,  -1,   0,  -1],
       [ -1,  -1,  -1,   0,  -1, 100],
       [ -1,  -1,  -1,   0,  -1,  -1],
       [ -1,   0,   0,  -1,   0,  -1],
       [  0,  -1,  -1,   0,  -1, 100],
       [ -1,   0,  -1,  -1,   0, 100]])